repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
        stages: [pre-commit]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: commit message check
        name: commit message check
        entry: sh
        language: system
        stages: [commit-msg]
        always_run: true
        args:
          - "scripts/check_commit_message.sh"
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [python]
        stages: [pre-commit]
        require_serial: true
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--remove-all-unused-imports"
